from snakemake.utils import min_version

#------------- min snakemake version ------------
min_version('6.7.0')

#------------- setup ------------
configfile: 'config/config.yaml'

report: 'report/workflow.rst'

check_contamination = bool(config['check_contamination'])

#------------- load rules ------------

include: 'rules/common.smk'
include: 'rules/preprocess.smk'
include: 'rules/align.smk'
include: 'rules/consensus.smk'
include: 'rules/qc.smk'
include: 'rules/variants.smk'

if check_contamination:
    include: 'rules/contamination.smk'

if config['umis'] != '':
    include: 'rules/umi_correct.smk'
else:
    include: 'rules/umi.smk'


#------------- workflow ------------

if check_contamination:
    rule all:
        input:
            get_varcall_output(),
            get_assembly_output(),
            'results/QC/checkm/stats.txt',
            'results/QC/multiQC/multiqc_report.html',
            'results/QC/consensus/multiQC/multiqc_report.html'
else:
    rule all:
        input:
            get_varcall_output(),
            'results/QC/multiQC/multiqc_report.html',
            'results/QC/consensus/multiQC/multiqc_report.html'
