bcl2fastq:
    threads: 16
    mem_mb: 98304
    runtime: '0-12:0:0'

mergelanes:
    threads: 1
    mem_mb: 12288
    runtime: '0-2:0:0'

fastqc:
    threads: 2
    mem_mb: 8192
    runtime: '0-12:0:0'

fastqscreen:
    threads: 8
    mem_mb: 32768
    runtime: '1-0:0:0'

multiqc:
    threads: 1
    mem_mb: 65536
    runtime: '0-12:0:0'

bwa:
    threads: 16
    mem_mb: 36864
    runtime: '0-12:0:0'

samtools_stats:
    threads: 1
    mem_mb: 8192
    runtime: '0-5:0:0'

qualimap:
    threads: 8
    mem_mb: 8192
    runtime: '0-5:0:0'

picard:
    threads: 1
    mem_mb: 98304
    runtime: '1-0:0:0'
    max_records_in_ram: 100000

getreadinfo:
    threads: 16
    mem_mb: 131072
    runtime: '1-0:0:0'
    buffer_size: '110G'

formatreadinfo:
    threads: 1
    mem_mb: 49152
    runtime: '0-12:0:0'

fgbio:
    threads: 1
    mem_mb: 65536
    runtime: '0-12:0:0'

varscan:
    threads: 1
    mem_mb: 32768
    runtime: '1-0:0:0'
