# config file for Fastq Screen
FastqScreen_config: config/fastq_screen.conf

# config file for MultiQC
multiqc_config: config/multiqc_config.yaml

# reference genome fasta
ref: 'ref/Ecoli_strain_BL21_genome.fasta' 

# file of UMI sequences, one per line
# set to empty string if UMIs are unknown
# used to correct UMI sequences
#umis: 'metadata/umis.txt'
umis: ''

# max number of UMI mismatches
# used only if correcting UMIs
max_mismatches: 3

# min distance in mismatches to next best UMI
# used only if correcting UMIs
min_distance: 1

# read structure for each strand, e.g.
# 3M2S146T = 3 UMI, 2 skipped, 146 read
# bases (--read-structure argument used
# by fgbio's ExtractUmisFromBam)
read_structure: '3M2S146T 3M2S146T'
#read_structure: '8M143T 8M143T'

# SAM tag(s) in which to store the molecular
# indices (--molecular-index-tag argument used by
# fgbio's ExtractUmisFromBam)
molecular_index_tags: 'ZA ZB'

# Single tag into which to concatenate all
# molecular indices. Corresponds to fgbio's
# --single-tag argument
single_tag: 'RX'

# Minimum mapping quality used by fgbio's
# GroupReadsByUmi (--min-map-q)
min_mapq: 20

# Minimum base quality used by fgbio's
# CallDuplexConsensusReads (--min-input-base-quality)
min_input_baseq: 30

# Phred-scaled error rate for an error prior
# to the UMIs being integrated, used by fgbio's
# CallDuplexConsensusReads (--error-rate-pre-umi)
error_rate_pre_umi: 45

# Phred-scaled error rate for an error post
# the UMIs having been integrated, used by fgbio's
# CallDuplexConsensusReads (--error-rate-post-umi)
error_rate_post_umi: 40

# Minimum number of reads supporting a consensus base/read
# used in fgbio's FilterConsensusReads (--min-read)
min_reads: '4 2 2'

# Maximum raw-read error rate across the entire consensus read
# used in fgbio's FilterConsensusReads (--max-read-error-rate)
max_read_error_rate: 0.05

# Maximum error rate for a single consensus base
# used in fgbio's FilterConsensusReads (--max-base-error-rate)
max_base_error_rate: 0.1

# Mask (make 'N') consensus bases with quality less than this
# threshold
# used in fgbio's FilterConsensusReads (--min-base-quality)
min_base_quality: 50

# Maximum fraction of no-calls in the read after filtering
# used in fgbio's FilterConsensusReads ( --max-no-call-fraction)
max_no_call_fraction: 0.05

# minimum duplex coverage to call a variant
min_coverage: 4

# min supporting duplex reads to call a variant
min_reads2: 2

# minimum duplex VAF to call a variant
min_vaf: 0.01
